### ISSUE TITLE
Problemas na implementação do projeto

### ISSUE THREAD

**Issue by resucutie** [felipemarinho97/torrent-indexer#27]
Bom dia. Estava tentando implementar este indexer, mas, após configurar o meilisearch e o flare-bypasser, ele me retorna uma lista vazia

![Image](https://github.com/user-attachments/assets/9f1a1aa0-9be0-435c-888a-8267c792fe92)

docker composer:
```yaml
version: '3'

services:
  torrent-indexer:
    image: felipemarinho97/torrent-indexer:latest
    container_name: torrent-indexer
    restart: unless-stopped
    ports:
      - 7006:7006
    networks:
      - torrent-indexer
    environment:
      - REDIS_HOST=redis
      - MEILISEARCH_ADDRESS=http://meilisearch:7700
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - FLARESOLVERR_ADDRESS=http://192.168.0.2:8191
  
  redis:
    image: redis:alpine
    container_name: redis-indexer
    restart: unless-stopped
    networks:
      - torrent-indexer

  # This container is not necessary for the indexer to work,
  # deploy if you want to use the search feature
  meilisearch: 
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    networks:
      - torrent-indexer
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY

networks:
  torrent-indexer:
    external: true
```
