### ISSUE TITLE
Não consigo configurar meu Jackett nem o Sonnar

### ISSUE THREAD

**Issue by AndersonSheep** [felipemarinho97/torrent-indexer#8]
Cara eu sou meio novo com isso de configurar tracker. Não achei como posso adicionar um link personalizado no Jackett. 

Teria como você gravar um vídeo mostrando como fazer essa configuração? Só pelo tutorial não consegui :/

**Comment by Thanegche** [comment]
Para adicionar torrent Index no jackett vc tem que acha a pasta onde fica os outros tracker e depois adicionar o arquivo da página inicial do torrent Index como arquivo yml e depois reiniciar o jackett ele vai aparecer na lista de Tracker Br se estiver com dificuldade me chame no Discord thanegche q te ajudo

**Comment by MrMoreira** [comment]
Cara não consigo instalar, já tentei adicionar bludv.json, bludv.yml, bludv.yaml e toda vez q reinicio ele deleta o bludv.json, e não funciona não aparece na lista de trackers brasileiros, podeiria me ajudar, te mandei solicitação no discord.
/mnt/jackett/data/Jackett/Indexers
discord: mrmoreira

**Comment by felipemarinho97** [comment]
@MrMoreira aqui eu uso com uma bind mound do Docker da seguinte maneira e funciona bem:

```
[...]

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /opt/jackett/data:/config
      - /opt/jackett/blackhole:/downloads
      - /opt/jackett/comando-indexer.yml:/app/Jackett/Definitions/comando-indexer.yml
      - /opt/jackett/bludv-indexer.yml:/app/Jackett/Definitions/bludv-indexer.yml
    ports:
      - 9117:9117
    restart: unless-stopped

```
